title: "Androit"
description: "Your go-to source for opportune insights and an optimized information tapestry."
baseurl: "" # leave this blank
url: "https://TheAndroit.github.io/TheAndroit" # replace with your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima

# Gems
plugins:
  - jekyll-feed

# Optional settings for the Minima theme
minima:
  # Enables or disables minima-syntax-highlighting
  syntax_highlighting: true
  # Custom theme colors
  skin: dark

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include additional files
include:
  - _pages
  - _posts
  - assets

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Default Author"

# Markdown settings
kramdown:
  input: GFM
  hard_wrap: false